[workspace]
resolver = "3"
members = ["bins/*","crates/*"]
default-members = ["bins/*", "crates/*"]

[workspace.package]
version = "0.0.0"
edition = "2024"
license = "MIT"
readme = "README.md"
authors = ["Alexander Acebo <aacebowork@gmail.com>"]
categories = []
repository = "https://github.com/aacebo/nim"

[workspace.lints.clippy]
large_enum_variant = "allow"
type_complexity = "allow"
new_without_default = "allow"

[workspace.dependencies]
chrono = { version = "0.4", features = ["serde"] }
sqlx = { version = "0.9", default-features = false }
uuid = { version = "1", features = ["v7", "serde"] }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1" }
serde_valid = { version = "2" }
tokio = { version = "1" }
tracing = { version = "0.1" }
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }

nim = { path = "crates/nim", version = "0.0.0" }
nim-mem = { path = "crates/nim-mem", version = "0.0.0" }
nim-state = { path = "crates/nim-state", version = "0.0.0" }
nim-store = { path = "crates/nim-store", version = "0.0.0" }
