name: nim

services:
  postgres:
    container_name: nim-postgres
    image: pgvector/pgvector:pg17
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: main
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    healthcheck:
      test: pg_isready -U admin -d main
      interval: 10s
      timeout: 5s
      retries: 5

  audio:
    container_name: nim-audio
    image: rust:alpine
    command: cargo run -p nim-audio --release
    working_dir: /app
    ports:
      - 3000:8080
    environment:
      DATABASE_URL: postgres://admin:admin@postgres:5432/main
    volumes:
      - type: bind
        source: ./
        target: /app
    depends_on:
      postgres:
        condition: service_healthy

  exec:
    container_name: nim-exec
    image: rust:alpine
    command: cargo run -p nim-exec --release
    working_dir: /app
    ports:
      - 3001:8080
    environment:
      DATABASE_URL: postgres://admin:admin@postgres:5432/main
    volumes:
      - type: bind
        source: ./
        target: /app
    depends_on:
      postgres:
        condition: service_healthy

  vision:
    container_name: nim-vision
    image: rust:alpine
    command: cargo run -p nim-vision --release
    working_dir: /app
    ports:
      - 3002:8080
    environment:
      DATABASE_URL: postgres://admin:admin@postgres:5432/main
    volumes:
      - type: bind
        source: ./
        target: /app
    depends_on:
      postgres:
        condition: service_healthy
